spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
  liquibase:
    change-log: classpath:/liquibase/changelog.xml

jwt:
  secret: bSxua2pramd5dWdjdGZnZ2ZkZmhnbmN4Y2N0anl0ZmhnY2Z5dXQ3NjVydGRnZmNoanU3NjVydGRmZ2dmZGZoZ25jeGNjdGp5dGZoZ2NmeXV0NzY1cnRkZ2ZjaGp1NzY1cnRkZmdnZmRmaGduY3hj
  expiration: 600000
upload:
  image:
    path: C:\\Users\\Admin\\IdeaProjects\\library\\images\\